##------------##
## SConstruct ##
##-------------------------------------------------------##
## author: Jaegwang Lim @ Dexter Studios                 ##
## last update: 2018.01.11                               ##
##-------------------------------------------------------##

import os

if not os.path.exists( '../build/lib') : os.makedirs( '../build/lib' )
SConscript( 'SConscript.py', variant_dir='../build/lib', duplicate=0 )
